version: "3.8"

services:
  ingest-service:
    build:
      context: .
      dockerfile: ingest-service/Dockerfile
    image: graph-analysis-ingest:latest
    container_name: ingest-service
    env_file:
      - ./.env
    ports:
      - "8001:8001"

  routing-service:
    build:
      context: .
      dockerfile: routing-service/Dockerfile
    image: graph-analysis-routing:latest
    container_name: routing-service
    env_file:
      - ./.env
    environment:
      - INGEST_SERVICE_URL=http://ingest-service:8001/export-graph
    ports:
      - "8002:8002"
